
bands:

  band_1:
    file_path: "./1st.fits"
    background_mode: "const"
    move_factor: 5
    area_ratio: 0.90
    s_sigma: 4.0
    G_fit: false
    skip_reduction: true

  band_2:
    file_path: "./2nd.fits"
    background_mode: "morph"
    move_factor: 8
    area_ratio: 0.90
    s_sigma: 4.0
    G_fit: true
    skip_reduction: false

  band_3:
    file_path: "./3rd.fits"
    background_mode: "const"
    move_factor: 8
    area_ratio: 0.93
    s_sigma: 2.7
    G_fit: true
    skip_reduction: true

  band_4:
    file_path: "./4th.fits"
    background_mode: "const"
    move_factor: 3
    area_ratio: 0.93
    s_sigma: 3.13
    G_fit: false
    skip_reduction: true


